const colors=['peach','yellow','lavender','mint','blue'];
let places=[], picks=[];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=t=>/火锅|串/.test(t)?'🍲':/烧烤|烤肉/.test(t)?'🍢':/日式|拉面|寿司/.test(t)?'🍜':/甜品|蛋糕|奶茶/.test(t)?'🍰':/咖啡|茶/.test(t)?'☕':/辣|湘|川/.test(t)?'🌶️':'✨';
async function load(){const r=await fetch('/api/places',{cache:'no-store'});if(!r.ok)throw new Error('加载失败');const rows=await r.json();places=rows;picks=rows.filter(x=>x.selected).map(x=>x.id)}
function savePicks(){void fetch('/api/picks',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({placeIds:picks})})}
function home(){document.querySelector('#app').innerHTML=`<main class="shell"><header class="topbar"><div class="brand"><span class="brand-mark">🥢</span>小林小郑吃好吃的</div><a href="#list">看看收藏</a></header><section class="hero"><p class="eyebrow">FOOD MOOD · 01</p><h1>今天<span>吃好吃的</span></h1><p class="sub">选择困难没关系，菜单替你操心</p></section><section class="card"><div class="section-head"><div><h2>想吃什么</h2><p>先圈起来，纠结稍后再说</p></div><span class="count">${picks.length} 家</span></div><div class="places">${places.map(placeButton).join('')}</div>${places.length?'':'<div class="empty">🍽️<p>候选席位空着，等你点名</p><a href="#list">去收藏里加几家 →</a></div>'}</section><section class="draw-area"><button class="draw-btn" id="draw" ${picks.length?'':'disabled'}>🎲 随便挑一家</button><p class="hint">点一下，看看今天的胃口有什么主意</p></section></main>`;bindHome()}
function placeButton(p){let chosen=picks.includes(p.id);return `<button class="place ${p.color} ${chosen?'chosen':''}" data-pick="${p.id}"><span class="food">${p.emoji}</span><span class="place-copy"><strong>${esc(p.name)}</strong><small>${esc(p.tag)}</small></span><span class="check">${chosen?'✓':''}</span></button>`}
function bindHome(){document.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{let id=+b.dataset.pick;picks=picks.includes(id)?picks.filter(x=>x!==id):[...picks,id];savePicks();home()});document.querySelector('#draw').onclick=()=>{let pool=places.filter(p=>picks.includes(p.id));if(!pool.length)return;showResult(pool[Math.floor(Math.random()*pool.length)])}}
function showResult(p){let d=document.createElement('div');d.className='backdrop';d.innerHTML=`<div class="modal"><p class="eyebrow">TODAY'S PICK</p><div class="result-food">${p.emoji}</div><p>抽到的是</p><h2>${esc(p.name)}</h2><p>${esc(p.tag)}</p><button class="again">不服，再抽</button><button class="close">行，就它了</button></div>`;document.body.append(d);d.querySelector('.close').onclick=()=>d.remove();d.querySelector('.again').onclick=()=>{d.remove();document.querySelector('#draw').click()};d.onclick=e=>{if(e.target===d)d.remove()}}
function list(){document.querySelector('#app').innerHTML=`<main class="shell"><header class="topbar"><div class="brand">📒 美食清单</div><a href="#">回到选择 (${picks.length}) →</a></header><section class="hero"><p class="eyebrow">MY FOOD LIBRARY</p><h1>把想吃的，<span>先记下来。</span></h1></section><section class="card"><div class="section-head"><div><h2>我的美食收藏</h2><p>想到什么就收什么</p></div><span class="count">${places.length} 家</span></div><div class="places">${places.map(p=>`<div class="place ${p.color}"><span class="food">${p.emoji}</span><span class="place-copy"><strong>${esc(p.name)}</strong><small>${esc(p.tag)}</small></span><button class="candidate ${picks.includes(p.id)?'active':''}" data-toggle="${p.id}">${picks.includes(p.id)?'已选中 ✓':'加入选择'}</button><button class="delete" data-delete="${p.id}">×</button></div>`).join('')}</div><div class="add-form"><h3>再记一家</h3><input id="name" placeholder="店名或想吃的美食"><input id="tag" placeholder="随手写个类型（可选）"><button class="draw-btn" id="add">＋ 放进清单</button></div></section></main>`;bindList()}
function bindList(){document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{let id=+b.dataset.toggle;picks=picks.includes(id)?picks.filter(x=>x!==id):[...picks,id];savePicks();list()});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{let id=+b.dataset.delete;await fetch(`/api/places/${id}`,{method:'DELETE'});places=places.filter(x=>x.id!==id);picks=picks.filter(x=>x!==id);list()});document.querySelector('#add').onclick=async()=>{let n=document.querySelector('#name').value.trim(),t=document.querySelector('#tag').value.trim()||'未分类';if(!n)return;const r=await fetch('/api/places',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:n,tag:t,emoji:icon(t),color:colors[places.length%5]})});if(r.ok)places.push(await r.json());list()}}
function route(){location.hash==='#list'?list():home()}addEventListener('hashchange',route);load().then(route).catch(()=>{document.querySelector('#app').innerHTML='<main class="shell"><section class="card"><h2>数据加载失败</h2><p>请确认 EdgeOne KV 已绑定为 food_data。</p></section></main>'});
