"use client";
import {useEffect,useState} from "react";
type Place={id:number;name:string;tag:string;emoji:string;color:string};
const iconFor=(tag:string)=>{const t=tag.toLowerCase();if(/泰|thai/.test(t))return "🍛";if(/韩|korean/.test(t))return "🥘";if(/印|india|咖喱/.test(t))return "🍛";if(/越南|vietnam/.test(t))return "🍜";if(/墨西哥|mexican/.test(t))return "🌮";if(/意式|意大利|italian/.test(t))return "🍝";if(/法式|法国|french/.test(t))return "🥐";if(/土耳其|turkish/.test(t))return "🥙";if(/火锅|锅底|串串/.test(t))return "🍲";if(/烧烤|烤肉|串/.test(t))return "🍢";if(/日式|拉面|寿司|刺身/.test(t))return "🍜";if(/西式|汉堡|披萨|意面/.test(t))return "🍔";if(/中式|台式|粤|面|饭/.test(t))return "🍚";if(/湘|川|辣/.test(t))return "🌶️";if(/甜品|蛋糕|奶茶|甜/.test(t))return "🍰";if(/咖啡|饮品|茶/.test(t))return "☕";if(/海鲜/.test(t))return "🦀";return "✨"};
export default function List(){
 const[places,setPlaces]=useState<Place[]>([]),[picks,setPicks]=useState<number[]>([]),[name,setName]=useState(""),[tag,setTag]=useState("");
 useEffect(()=>{fetch("/api/places").then(r=>r.ok?r.json():Promise.reject()).then((data:unknown)=>{const rows=Array.isArray(data)?data as (Place&{selected?:number})[]:[];setPlaces(rows);setPicks(rows.filter(x=>x.selected).map(x=>x.id))}).catch(()=>{})},[]);
 const savePicks=(next:number[])=>{setPicks(next);void fetch("/api/picks",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({placeIds:next})})};
 const add=()=>{if(!name.trim())return;const cleanTag=tag.trim()||"未分类";void fetch("/api/places",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:name.trim(),tag:cleanTag,emoji:iconFor(cleanTag),color:["peach","yellow","lavender","mint","blue"][places.length%5]})}).then(r=>r.json()).then((p:Place)=>{setPlaces(x=>[...x,p]);setName("");setTag("")})};
 const remove=(id:number)=>{void fetch(`/api/places/${id}`,{method:"DELETE"});setPlaces(places.filter(x=>x.id!==id));setPicks(picks.filter(x=>x!==id));};
 const toggle=(id:number)=>savePicks(picks.includes(id)?picks.filter(x=>x!==id):[...picks,id]);
 return <main className="shell"><header className="topbar"><div className="brand"><span className="brand-mark">📒</span><span>美食清单</span></div><a href="/" className="text-link">回到选择 ({picks.length}) →</a></header><section className="hero"><p className="eyebrow">MY FOOD LIBRARY</p><h1>把想吃的，<span>先记下来。</span></h1><p className="sub">收集多多多的美味</p></section><section className="card picker"><div className="section-head"><div><h2>我的美食收藏</h2><p>想到什么就收什么，清单不会嫌多</p></div><span className="count">{places.length} 家</span></div><div className="places">{places.map(x=><div className={`place ${x.color}`} key={x.id}><span className="food">{x.emoji}</span><span className="place-copy"><strong>{x.name}</strong><small>{x.tag}</small></span><button className={`candidate-btn ${picks.includes(x.id)?"active":""}`} onClick={()=>toggle(x.id)}>{picks.includes(x.id)?"已选中 ✓":"加入选择"}</button><button className="delete" aria-label={`删除${x.name}`} onClick={()=>remove(x.id)}>×</button></div>)}</div><div className="add-form"><h3>再记一家</h3><input placeholder="店名或想吃的美食" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="随手写个类型（可选）" value={tag} onChange={e=>setTag(e.target.value)}/><button className="draw-btn" onClick={add}>＋ 放进清单</button></div></section></main>
}
